### PR TITLE
javascript-2-a extension exercise

### PR DESCRIPTION
**Pull request by mmmmmrob**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SleeplessByte Would you mind looking at this PR?

**Comment by mmmmmrob** [comment]
@ErikSchierboom I noted as WIP as entirely expected to have missed something. Happy for a merge if you're happy.

**Comment by ErikSchierboom** [comment]
Thanks a ton for doing this @mmmmmrob! 🎉

**Comment by iHiD** [comment]
Thanks @mmmmmrob! :)

**Pull request merged**
