### PR TITLE
x86-64-assembly: Add troubleshooting section

### PR DESCRIPTION
**Pull request by bergjohan**
Should `%include "debug.asm"` be added to the stub files?

### CODE REVIEW

**Comment by bergjohan** [comment]
The experiment is only in-browser coding, right? Otherwise the "debug.asm" file wont be found since it's inside the Docker image.

**Comment by ErikSchierboom** [comment]
> The experiment is only in-browser coding, right?

It is!

**Comment by ErikSchierboom** [comment]
@bergjohan FYI There are two merge conflicts.

**Comment by bergjohan** [comment]
Resolved the merge conflict and added `%include "debug.asm"` to the stub files. There will probably be another merge conflict if #46 is merged though.

**Comment by ErikSchierboom** [comment]
Thanks @bergjohan!

**Pull request merged**
